UPDATE timetable_slot
SET grade = CASE grade
  WHEN '초1' THEN 'ELEMENTARY_1'
  WHEN '초2' THEN 'ELEMENTARY_2'
  WHEN '초3' THEN 'ELEMENTARY_3'
  WHEN '초4' THEN 'ELEMENTARY_4'
  WHEN '초5' THEN 'ELEMENTARY_5'
  WHEN '초6' THEN 'ELEMENTARY_6'
  WHEN '중1' THEN 'MIDDLE_1'
  WHEN '중2' THEN 'MIDDLE_2'
  WHEN '중3' THEN 'MIDDLE_3'
  WHEN '고1' THEN 'HIGH_1'
  WHEN '고2' THEN 'HIGH_2'
  WHEN '고3' THEN 'HIGH_3'
  ELSE grade
END;

ALTER TABLE timetable_slot
  MODIFY grade VARCHAR(20) NOT NULL;
