ALTER TABLE calendar_events ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE timetable_slot ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE timetable_set ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
