package com.academy.mudogroupware.attendance.infrastructure.query;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDate;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.jdbc.Sql;

@JdbcTest(properties = {
        "spring.flyway.enabled=false",
        "spring.datasource.url=jdbc:h2:mem:attendance-query;MODE=MySQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=ROLE"
})
@Import({WeeklyAttendanceQueryAdapter.class, TeamAttendanceQueryAdapter.class})
@Sql(statements = {
        "CREATE TABLE role (role_id BIGINT PRIMARY KEY, name VARCHAR(50) NOT NULL)",
        "CREATE TABLE users (id BIGINT PRIMARY KEY, name VARCHAR(50) NOT NULL, role_id BIGINT, "
                + "status VARCHAR(20) NOT NULL, account_type VARCHAR(20) NOT NULL, admin_scope VARCHAR(20))",
        "CREATE TABLE attendance_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "user_id BIGINT NOT NULL, work_date DATE NOT NULL, clock_in_at TIMESTAMP, "
                + "clock_out_at TIMESTAMP, status VARCHAR(20))"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_CLASS)
class AttendanceEmployeeQueryAdapterTest {

    private static final long REQUESTER_ID = 1L;
    private static final LocalDate WORK_DATE = LocalDate.of(2026, 8, 16);

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private WeeklyAttendanceQueryAdapter weeklyAttendanceQueryAdapter;

    @Autowired
    private TeamAttendanceQueryAdapter teamAttendanceQueryAdapter;

    @BeforeEach
    void setUp() {
        jdbcTemplate.update("INSERT INTO role (role_id, name) VALUES (1, '직원')");
        insertUser(REQUESTER_ID, "요청자", "MEMBER", null);
        insertUser(2L, "일반 직원", "MEMBER", null);
        insertUser(3L, "슈퍼 어드민", "ADMIN", "PLATFORM");
        insertUser(4L, "학원 관리자", "ADMIN", "ACADEMY");
    }

    @Test
    void 전_직원_주간_근태_조회에서_슈퍼_어드민을_제외한다() {
        assertThat(weeklyAttendanceQueryAdapter.findEmployees(
                REQUESTER_ID, WORK_DATE.minusDays(6), WORK_DATE))
                .extracting(employee -> employee.userId())
                .containsExactly(2L, 4L);
    }

    @Test
    void 오늘_내_팀_근태_조회에서_슈퍼_어드민을_제외한다() {
        assertThat(teamAttendanceQueryAdapter.findEmployeesWithAttendance(REQUESTER_ID, WORK_DATE))
                .extracting(employee -> employee.userId())
                .containsExactly(2L, 4L);
    }

    private void insertUser(long id, String name, String accountType, String adminScope) {
        jdbcTemplate.update(
                "INSERT INTO users (id, name, role_id, status, account_type, admin_scope) "
                        + "VALUES (?, ?, ?, 'ACTIVE', ?, ?)",
                id, name, accountType.equals("MEMBER") ? 1L : null, accountType, adminScope);
    }
}
